### ISSUE TITLE
File Browser Upload images fail

### ISSUE THREAD

**Issue by charlyfriend** [magicbruno/FileBrowser#1]
I setted File Browser to use with ckeditor.
When I try to upload images, an error appear: "User does not have sufficient privileges."
How can I haven't privileges if I can create folders inside Images folder?
I setted "Everyone" privileges over my custom folder with full control.
I'm working in development with VS2013.
I was debbuging MyUpload.ashx
If I comment this code, File Browser upload my pics fine:
        else if (!MagicSession.Current.Upload)
        {
             response.success = false;
             response.exitcode = 3;
             response.msg = GetResource("Upload_Error_3", culture, "User does not have sufficient privileges.");
         }

**Comment by magicbruno** [comment]
You have to set MB.FileBrowser.MagicSession.Current.FileBrowserAccessMode public property to modify user access prerogatives (AccessMode.ReadOnly for default). 
MagicSession.Current.Upload  is used internally to check if user has upload rights. If you are using CkEditor on public site probably you may have users with read-write rights, users with read-only rights and users with non rights. You can handle this changing MB.FileBrowser.MagicSession.Current.FileBrowserAccessMode on login process.
Sure, if you want, you can set MB.FileBrowser.MagicSession.Current.FileBrowserAccessMode to AccessMode.Write on every page and open read-write access to everione.
