### ISSUE TITLE
SelectedItemsAction issue

### ISSUE THREAD

**Issue by kl7323** [magicbruno/FileBrowser#12]
IZ.WebfileManager has a method SelectedItemsAction that allows me to intercept the delete call.  I need to do this because I have a dual server setup and need to delete files on both server.  

I have been able to make the same call via your test site without issue.  However when I make the same call from the downloaded code from Nuget I receive the following error:

Compiler Error Message: CS1061: 'ASP.filebrowser_filebrowser_aspx' does not contain a definition for 'FileManager1_SelectedItemsAction' and no extension method 'FileManager1_SelectedItemsAction' accepting a first argument of type 'ASP.filebrowser_filebrowser_aspx' could be found (are you missing a using directive or an assembly reference?)

Here is my declaration
<iz:FileManager ID="FileManager1" runat="server" Height="480" Width="570" ImagesFolder="~/FileBrowser/img/cmd"
                MainDirectory="~/assets/" CustomThumbnailHandler="~/FileBrowser/IZWebFileManagerThumbnailHandler.ashx"
                ShowHiddenFilesAndFolders="false" FileViewMode="Thumbnails" ClientOpenItemFunction="fileSelected" OnSelectedItemsAction="FileManager1_SelectedItemsAction"
                DefaultAccessMode="Write" > 
                <ToolbarOptions 
                 ShowCopyButton="false" 
                 ShowDeleteButton="false"
                 ShowFolderUpButton="true"
                 ShowMoveButton="false"
                 ShowNewFolderButton="false"
                 ShowRefreshButton="true"
                 ShowRenameButton="false"
                 ShowViewButton ="true"             
                 />
                <CustomToolbarButtons>
                    <iz:CustomToolbarButton ImageUrl="img/cmd/Show.png" Text="Mostra file" PerformPostBack="false"
                        OnClientClick="showFile()" />
                </CustomToolbarButtons>
                <FileTypes>
                    <iz:FileType Extensions=".jpg, .jpeg,.png, .gif"                            SmallImageUrl="img/16/file-picture.png"         LargeImageUrl="img/32/file-picture.png"></iz:FileType>
                    <iz:FileType Extensions=".xls,.xlsx,.ods"                                   SmallImageUrl="img/16/file-excel-alt.png"       LargeImageUrl="img/32/file-excel-alt.png"></iz:FileType>
                    <iz:FileType Extensions=".pdf"                                              SmallImageUrl="img/16/file-pdf-alt.png"         LargeImageUrl="img/32/file-pdf-alt.png"> </iz:FileType>
                    <iz:FileType Extensions=".txt"                                              SmallImageUrl="img/16/file-text.png"            LargeImageUrl="img/32/file-text.png"></iz:FileType>
                    <iz:FileType Extensions=".doc,.docx,.odt"                                   SmallImageUrl="img/16/file-word-alt.png"        LargeImageUrl="img/32/file-word.png"></iz:FileType>
                    <%--<ValidfileFormats>.doc,.docx,.rtf,.txt,.ppt,.pps,.pptx,.xls,.xlsx,.csv,.txt,.htm,.jpg,.jpeg,.gif,.png,.swf,.flv,.pdf,.bmp</ValidfileFormats>
                     <iz:FileType Extensions=".psd"                                              SmallImageUrl="img/16/file-photoshop.png"       LargeImageUrl="img/32/file-photoshop.png"></iz:FileType>
                    <iz:FileType Extensions=".ppt,.pptx,.pptm, .odp"                            SmallImageUrl="img/16/file-powerpoint-alt.png"  LargeImageUrl="img/32/file-powerpoint-alt.png"></iz:FileType>
                    <iz:FileType Extensions=".aiff,.mp3,.ogg,.oga,.wav,.wma"                    SmallImageUrl="img/16/file-sound.png"           LargeImageUrl="img/32/file-sound.png"></iz:FileType>
                    <iz:FileType Extensions=".flv,.f4v,.avi,.mov,.qt,.wmv,.mp4,.mpg,.mpeg,.mp2" SmallImageUrl="img/16/file-video.png"           LargeImageUrl="img/32/file-video.png"></iz:FileType>
                    <iz:FileType Extensions=".tar.gz, .7z, .ace, .cab, .rar, .zip, .zipx"       SmallImageUrl="img/16/file-zip-alt.png"         LargeImageUrl="img/32/file-zip-alt.png"></iz:FileType>--%>
                </FileTypes>
            </iz:FileManager>

Here is the code behind:

protected void FileManager1_SelectedItemsAction(object sender, SelectedItemsActionCancelEventArgs e) {
            if (e.Action == SelectedItemsAction.Open) {
                FileManagerItemInfo item = e.SelectedItems[0];

                if (VirtualPathUtility.GetFileName(item.VirtualPath).StartsWith("_")) {
                    e.Cancel = true;
                    e.ClientMessage = "Access Deny!";
                }
            }
            if (e.Action == SelectedItemsAction.Delete) {
                        e.Cancel = true;
                        e.ClientMessage = "Stopping the delete!";
            }
        }

**Comment by magicbruno** [comment]
FileBrowser Nuget distribution is the  compiled, ready to use,  version. Installing the package you will register FileBrowser.dll and install the files needed to open FileBrowser window, In this version FileBrowser.aspx code behind is already compiled in FileBrowser.dll. If you want change FileBrowser.aspx code behind you must use GitHub version.
