### ISSUE TITLE
Bug when uploading a file with existing filename

### ISSUE THREAD

**Issue by cmfbento** [magicbruno/FileBrowser#2]
there is a bug in "Myupload.ashx" when you try to upload a file , and exists on server another file with the same filename ....

Must change Line59

FROM:
    destPath = Path.GetFileNameWithoutExtension(destPath) + "(" + i.ToString() + ")" + Path.GetExtension(destPath);

TO:
 string filename1 = Path.GetFileNameWithoutExtension(filename) + "(" + i.ToString() + ")" + Path.GetExtension(filename);
                            destPath = context.Server.MapPath(VirtualPathUtility.AppendTrailingSlash(imagepath) + filename1);

**Comment by magicbruno** [comment]
Thanks for the notice. Bug is fixed in version 1.1.8.
