### ISSUE TITLE
Any source code for IZ.WebFileManager.dll and FileBrowser.dll?

### ISSUE THREAD

**Issue by ZiadJ** [magicbruno/FileBrowser#3]
I couldn't not find the source code for the the DLLs included in the Nuget package. I had the impression this project is fully open source or am I missing something?

**Comment by magicbruno** [comment]
https://github.com/manishma/IZWebFileManager 
https://github.com/magicbruno/IZWebFileManager
https://github.com/magicbruno/FileBrowser
