### ISSUE TITLE
Two issues with MB.FileBrowser 1.1.3

### ISSUE THREAD

**Issue by zhunter** [magicbruno/FileBrowser#4]
Just wanted to share two issues I've found when trying to use MB.FileBrowser via NuGet .
1. /FileBrowser/FileBrowser.aspx, FileManager1 shows ClientOpenItemFunction="showfile".  This causes nothing to happen when you click the photo in the file browser window.  To fix, change "showfile" to "fileSelected" and it will select and load the path into TinyMCE.
2. Typo in /FileBrowser/FileBrowser.aspx, the first set of FileTypes for FileManager1 has ".pmg" this should be ".png".

With those two changes, I can install TinyMCE & MB.FileBrowswer via NuGet and copy your Tiny MCE init sample from the test site into a new web application and have everything work without any modifications.

**Comment by magicbruno** [comment]
1. ClientOpenItemFunction="showfile" is correct. The image should be opened in a bootstrap modal.
2. Thanks for the notice I will fix this soon.
