### ISSUE TITLE
Invalid file manager path

### ISSUE THREAD

**Issue by lesljr** [magicbruno/FileBrowser#5]
I created a duplicate of FileBrowser and when i try to set the main directory, I get a "Invalid file manager path" message. I checked the documentation, but couldn't figure out the issue. Am i overlooking something?

protected void Page_PreInit(object sender, EventArgs e)
        {
            getUploadPath();
        }

```
    void getUploadPath()
    {
        FileManager1.MainDirectory = "~/uploads";
    }
```

**Comment by magicbruno** [comment]
Error is thrown from IZWebFileManager component (https://github.com/manishma/IZWebFileManager).
Try to use an absolute path (like "/uploads").
