### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by HannibalZA** [magicbruno/FileBrowser#6]
Hi 
Love the FileBrowser, good work.

The only thing I can suggest as a matter of urgency is to tie the filebrowser to an option that looks for some sort of Administrative Session Variable to block any unauthenticated access.

Currently if one knows this fileBrowser is in use on a site, it is easy to sniff out where it is and then have access to the website's assets. Potentially malicious in the wrong hands.

**Comment by magicbruno** [comment]
You can control access to Filebrowser.aspx using **DefaultAccessMode** property and  **MB.FileBrowser.MagicSession.Current.FileBrowserAccessMode** session property.
Read last chapter of readme.md:
Default AccesMode is defined by the IZWebFileManager property **DefaultAccessMode**. (You can change this in Filebrowser.aspx)
Handling user log in you can grant him proper access setting **FileBrowserAccessMode session property**.
MB FileBrowser offer a typed interface to session variables. Through class MagicSession defined in MB.FileBrowser you che handle session properties related to MB_FileBrowser.
MB.FileBrowser.MagicSession.Current.FileBrowserAccessMode define granted access to MB FileBrowser. Valid value are:
**DenyAll**: no access is allowed. Try to open FileBrowser cause e "Insufficient user prerogative" warning.
**ReadOnly**: user can only browse and download files.
**Write**: user can copy and upload but not overwrite, move or delete files.
**Delete**: user has full control over files.

Here an example of DefaultAccessMode set to **DenyAll** when you are not logged in:
[http://memorialmazzoni.it/Filebrowser/Filebrowser.aspx](http://memorialmazzoni.it/Filebrowser/Filebrowser.aspx)
Here an example of DefaultAccessMode set to **ReadOnly** when you are not logged in:
[http://www.sisteminterattivi.org/Contenuti.aspx?p=91](http://www.sisteminterattivi.org/Contenuti.aspx?p=91)
