### ISSUE TITLE
从nuget中下载了新的版本，但是有很多问题

### ISSUE THREAD

**Issue by daves2009** [magicbruno/FileBrowser#7]
FileView 在一个TypeScript中已经定义了，但是FileManager生成的代码中还存在一个FileView变量。而这个变量是一个DOM对象，提示：FileView不是一个构造函数

**Comment by magicbruno** [comment]
I can't understand. Please in english!

**Comment by daves2009** [comment]
This problem has been solved. Thanks

**Comment by magicbruno** [comment]
I
