### ISSUE TITLE
Navigate the Tree in Specific Folder

### ISSUE THREAD

**Issue by waqar2012** [magicbruno/FileBrowser#8]
When open the FileBrowser and select the file and close. 

How can i reopen the fileBrowser in the same selected folder as previous.

Please guide me

**Comment by magicbruno** [comment]
At the moment it is'nt immediate. FileBrowser is an interface to third part control  IZWebFileManager, that I have cloned and modified. My main goal was to get a free file manager for CKEditor. So, at the moment, you can choose only to open FileBrowser on one of the root directories required by CKEditor (files, images, media and flash) using the **type** querystring parameter. If you close FileBrowser no trace of current directory is keeped. Of couse you can do more modifying the code.  However this enacement in on my to do list and, may be, it will be included in the next release.
