### ISSUE TITLE
Load balanced site error - serialization

### ISSUE THREAD

**Issue by kl7323** [magicbruno/FileBrowser#9]
Is it possible for you to deploy a serialized version of this?  I have it working perfectly on my local visual studio server but cannot test it on my dev or test servers due to them being load balanced.  

The specific error is:  [SerializationException: Type 'MB.FileBrowser.MagicSection' in Assembly 'FileBrowser, Version=1.0.0.0, culture=neutral, PublicKeyToken=null' is not marked as serializable.]

I attempted to work with your source code however when I go to manishma/IZWebFileManager I see you requested a lot of modifications that were never included in his source.  

If I could get these modifications from you I can work on making the changes I need.

![serializationerror](https://cloud.githubusercontent.com/assets/21339094/19003029/912c06ae-8714-11e6-9c37-cfd9ada93869.PNG)

**Comment by magicbruno** [comment]
I never worked with loading balanced server and I can't test it. Some MagicSession properties can't be serializable because some values are created dinamically. In a future version, may be, I'll change this. However the code is shared and you may pull a request,
